import { PromptState, OptionType } from './types';

export const WAKTU_OPTIONS: OptionType[] = [
  { value: "", label: "Pilih Waktu (Opsional)" },
  { value: "pagi hari", label: "Pagi Hari" },
  { value: "siang hari", label: "Siang Hari" },
  { value: "sore hari", label: "Sore Hari" },
  { value: "malam hari", label: "Malam Hari" },
  { value: "matahari terbit", label: "Matahari Terbit (Sunrise)" },
  { value: "matahari terbenam", label: "Matahari Terbenam (Sunset)" },
  { value: "jam emas", label: "Jam Emas (Golden Hour)" },
  { value: "jam biru", label: "Jam Biru (Blue Hour)" },
];

export const GERAKAN_KAMERA_OPTIONS: OptionType[] = [
  { value: "", label: "Pilih Gerakan Kamera (Opsional)" },
  // Common movements
  { value: "static_shot", label: "Static Shot (Tangkapan Statis)" },
  { value: "pan_left", label: "Pan Left (Geser Kiri)" },
  { value: "pan_right", label: "Pan Right (Geser Kanan)" },
  { value: "pan_up", label: "Pan Up (Geser Atas)" },
  { value: "pan_down", label: "Pan Down (Geser Bawah)" },
  { value: "tilt_up", label: "Tilt Up (Dongak ke Atas)" },
  { value: "tilt_down", label: "Tilt Down (Tunduk ke Bawah)" },
  { value: "dolly_in", label: "Dolly In (Maju Mendekat)" },
  { value: "dolly_out", label: "Dolly Out (Mundur Menjauh)" },
  { value: "truck_left", label: "Truck Left (Geser Lateral Kiri)" },
  { value: "truck_right", label: "Truck Right (Geser Lateral Kanan)" },
  { value: "pedestal_up", label: "Pedestal Up (Naik Vertikal)" },
  { value: "pedestal_down", label: "Pedestal Down (Turun Vertikal)" },
  { value: "zoom_in", label: "Zoom In (Perbesar)" },
  { value: "zoom_out", label: "Zoom Out (Perkecil)" },
  { value: "crane_shot", label: "Crane Shot (Tangkapan Derek)" },
  { value: "drone_shot", label: "Drone Shot (Tangkapan Drone)" },
  { value: "handheld_shot", label: "Handheld Shot (Tangkapan Genggam)" },
  { value: "pov_shot", label: "POV Shot (Sudut Pandang Orang Pertama)" },
  { value: "dutch_angle", label: "Dutch Angle (Sudut Miring)" },
  // Higgsfield.ai inspired movements
  { value: "zoom_in_slow", label: "Zoom In Slow (Perbesar Lambat)" },
  { value: "zoom_in_fast", label: "Zoom In Fast (Perbesar Cepat)" },
  { value: "zoom_out_slow", label: "Zoom Out Slow (Perkecil Lambat)" },
  { value: "zoom_out_fast", label: "Zoom Out Fast (Perkecil Cepat)" },
  { value: "pan_left_slow", label: "Pan Left Slow (Geser Kiri Lambat)" },
  { value: "pan_left_fast", label: "Pan Left Fast (Geser Kiri Cepat)" },
  { value: "pan_right_slow", label: "Pan Right Slow (Geser Kanan Lambat)" },
  { value: "pan_right_fast", label: "Pan Right Fast (Geser Kanan Cepat)" },
  { value: "tilt_up_slow", label: "Tilt Up Slow (Dongak Atas Lambat)" },
  { value: "tilt_up_fast", label: "Tilt Up Fast (Dongak Atas Cepat)" },
  { value: "tilt_down_slow", label: "Tilt Down Slow (Tunduk Bawah Lambat)" },
  { value: "tilt_down_fast", label: "Tilt Down Fast (Tunduk Bawah Cepat)" },
  { value: "rotate_cw_slow", label: "Rotate Clockwise Slow (Putar Searah Jarum Jam Lambat)" },
  { value: "rotate_cw", label: "Rotate Clockwise (Putar Searah Jarum Jam)" },
  { value: "rotate_cw_fast", label: "Rotate Clockwise Fast (Putar Searah Jarum Jam Cepat)" },
  { value: "rotate_ccw_slow", label: "Rotate Counter-Clockwise Slow (Putar Berlawanan Jarum Jam Lambat)" },
  { value: "rotate_ccw", label: "Rotate Counter-Clockwise (Putar Berlawanan Jarum Jam)" },
  { value: "rotate_ccw_fast", label: "Rotate Counter-Clockwise Fast (Putar Berlawanan Jarum Jam Cepat)" },
  { value: "rolling_shutter_horizontal", label: "Rolling Shutter Horizontal" },
  { value: "rolling_shutter_vertical", label: "Rolling Shutter Vertical" },
  { value: "horror_zoom", label: "Horror Zoom (Zoom Horor)" },
  { value: "dolly_zoom", label: "Dolly Zoom (Vertigo Effect)" },
  { value: "3d_rotation", label: "3D Rotation (Rotasi 3D)" },
  { value: "camera_shake", label: "Camera Shake (Kamera Bergetar)" },
  { value: "follow_shot", label: "Follow Shot (Tangkapan Mengikuti)" },
  { value: "arc_shot", label: "Arc Shot (Tangkapan Melengkung)" },
];

export const PENCAHAYAAN_OPTIONS: OptionType[] = [
  { value: "", label: "Pilih Pencahayaan (Opsional)" },
  { value: "cahaya alami", label: "Cahaya Alami (Natural Light)" },
  { value: "jam emas", label: "Jam Emas (Golden Hour)" },
  { value: "jam biru", label: "Jam Biru (Blue Hour)" },
  { value: "mendung", label: "Mendung (Overcast)" },
  { value: "pencahayaan studio", label: "Pencahayaan Studio (Studio Lighting)" },
  { value: "lampu neon", label: "Lampu Neon (Neon Lights)" },
  { value: "pencahayaan volumetrik", label: "Pencahayaan Volumetrik (Volumetric Lighting)" },
  { value: "bayangan dramatis", label: "Bayangan Dramatis (Dramatic Shadows)" },
  { value: "backlit", label: "Backlit (Cahaya dari Belakang)" },
  { value: "rim lighting", label: "Rim Lighting (Cahaya Tepi)" },
  { value: "cahaya lembut", label: "Cahaya Lembut (Soft Light)" },
  { value: "cahaya keras", label: "Cahaya Keras (Hard Light)" },
  { value: "ambient occlusion", label: "Ambient Occlusion" },
  { value: "pencahayaan film noir", label: "Pencahayaan Film Noir" },
];

export const GAYA_VIDEO_OPTIONS: OptionType[] = [
  { value: "", label: "Pilih Gaya Video (Opsional)" },
  { value: "fotorealistik", label: "Fotorealistik (Photorealistic)" },
  { value: "sinematik", label: "Sinematik (Cinematic)" },
  { value: "anime", label: "Anime" },
  { value: "kartun", label: "Kartun (Cartoon)" },
  { value: "cat air", label: "Cat Air (Watercolor)" },
  { value: "render 3D", label: "Render 3D (3D Render)" },
  { value: "pixel art", label: "Pixel Art" },
  { value: "impresionistik", label: "Impresionistik (Impressionistic)" },
  { value: "surealis", label: "Surealis (Surreal)" },
  { value: "cyberpunk", label: "Cyberpunk" },
  { value: "steampunk", label: "Steampunk" },
  { value: "seni fantasi", label: "Seni Fantasi (Fantasy Art)" },
  { value: "seni konsep", label: "Seni Konsep (Concept Art)" },
  { value: "estetika lo-fi", label: "Estetika Lo-fi (Lo-fi Aesthetic)" },
  { value: "film vintage", label: "Film Vintage (Vintage Film)" },
];

export const SUASANA_VIDEO_OPTIONS: OptionType[] = [
  { value: "", label: "Pilih Suasana Video (Opsional)" },
  { value: "ceria", label: "Ceria (Joyful)" },
  { value: "sedih", label: "Sedih (Sad)" },
  { value: "tegang", label: "Tegang (Tense)" },
  { value: "misterius", label: "Misterius (Mysterious)" },
  { value: "romantis", label: "Romantis (Romantic)" },
  { value: "damai", label: "Damai (Peaceful)" },
  { value: "energik", label: "Energik (Energetic)" },
  { value: "epik", label: "Epik (Epic)" },
  { value: "nostalgia", label: "Nostalgia (Nostalgic)" },
  { value: "menyeramkan", label: "Menyeramkan (Eerie/Creepy)" },
  { value: "megah", label: "Megah (Grandiose)" },
];

export const DEFAULT_PROMPT_STATE: PromptState = {
  subjek: '',
  aksi: '',
  ekspresi: '',
  tempat: '',
  waktu: 'jam emas',
  gerakanKamera: 'dolly_zoom',
  pencahayaan: 'sinematik',
  gayaVideo: 'fotorealistik',
  suasanaVideo: 'epik',
  suaraMusik: '',
  kalimatYangDiucapkan: '',
  detailTambahan: '',
  negativePrompt: 'buram, kualitas rendah, teks, tanda tangan, watermark',
};
